[package]
name    = "yazi"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi-to-tui        = "3.0.0"
anyhow             = "1.0.71"
async-channel      = "1.8.0"
base64             = "0.21.2"
console-subscriber = "0.1.9"
crossterm          = { version = "0.26.1", features = [ "event-stream" ] }
futures            = "0.3.28"
glob               = "0.3.1"
image              = "0.24.6"
indexmap           = "2.0.0"
libc               = "0.2.146"
md5                = "0.7.0"
notify             = { version = "6.0.1", default-features = false, features = [ "macos_fsevent" ] }
once_cell          = "1.18.0"
parking_lot        = "0.12.1"
ratatui            = "0.21.0"
serde              = { version = "1.0.164", features = [ "derive" ] }
serde_json         = "1.0.103"
signal-hook-tokio  = { version = "0.3.1", features = [ "futures-v0_3" ] }
syntect            = "5.0.0"
tokio              = { version = "1.28.2", features = [ "parking_lot", "macros", "rt-multi-thread", "sync", "fs", "process", "io-std", "io-util", "time" ] }
toml               = "0.7.4"
tracing            = "0.1.37"
tracing-appender   = "0.2.2"
tracing-subscriber = "0.3.17"
trash              = "3.0.3"
unicode-width      = "0.1.10"
xdg                = "2.5.0"

# [profile.release]
# strip = true
# lto   = true
# panic = "abort"
